Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian12"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.define "zkotbiS" do |vm|
    vm.vm.hostname = "zkotbiS"

    vm.vm.network "private_network", ip: "192.168.56.110"
    vm.vm.network "forwarded_port", guest: 80, host: 8080

    vm.vm.provision "shell", path: "scripts/install.sh"

    vm.vm.provider "libvirt" do |v|

      v.memory = 1024
      v.cpus = 1

    end
  end
end
