if !File.exist?("node-token")
  abort "Error: The file 'node-token' is required to proceed! and must include secrit token"
end

K3S_CLUSTER_TOKEN = File.read("node-token").strip

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian12"

  config.vm.box_check_update = false

  config.vm.define "zkotbiS" do |ctrl|

    ctrl.vm.hostname = "zkotbiS"
    ctrl.vm.network "private_network", ip: "192.168.56.110"
    ctrl.vm.provision "shell", path: "scripts/server.sh", env: {"K3S_TOKEN" => K3S_CLUSTER_TOKEN}

    ctrl.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "zkotbiSW" do |ctrl|

    ctrl.vm.hostname = "zkotbiSW"
    ctrl.vm.network "private_network", ip: "192.168.56.111"
    ctrl.vm.provision "shell", path: "scripts/worker.sh", env: {"K3S_TOKEN" => K3S_CLUSTER_TOKEN}

    ctrl.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

end
